config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end
  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h2>All our flats (<%= Flat.count %>)</h2>
<div class="container d-flex">
  <div class="row justify-content-md-center">
  <% @flats.each do |flat| %>
    <div class="card mr-3 mb-3" style="width: 18rem;">
      <div class="col">
        <div class="card-body">
          <img src="https://images.unsplash.com/photo-1513584684374-8bab748fbf90?ixlib=rb-1.2.1&auto=format&fit=crop&w=1046&q=80" />
          <div class="main-content">
            <h5 class="card-title"><%= flat.name %></h5>
            <p class="card-text"><%= flat.address %></p>
            <div class="info">
              <span><%= flat.number_of_guests %><i class="material-icons">people</i></span><span><%= flat.price_per_night %><i class="material-icons">euro_symbol</i></span>
            </div>
          </div>
          <div class="link-flat">
            <a class="card-link"><%= link_to 'More info', flat_path(flat) %></a>
          </div>
        </div>
      </div>
    </div>
      <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h2>Rent your flat</h2>

<div class="container">
  <%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <%= f.button :submit %>
    <% end %>

</div>

app/views/flats/show.html.erb
<div class="banner" style="background-image: url(https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80);">
  <div class="container">
  </div>
</div>

<div class="container-show">
  <div class="content">
    <div class="flat-title">
      <h2> <%= Flat.find(params[:id]).name %> </h2>
      <p><%= Flat.find(params[:id]).address %></p>
    </div>
    <div class="flat-description">
      <h4> A bit more about this flat... </h4>
      <p><%= Flat.find(params[:id]).description %></p>
      <div id='map' style='width: 400px; height: 300px;'></div>
    </div>
    <div class="flat-details">
      <h4> Details </h4>
      <p><%= Flat.find(params[:id]).number_of_guests %><i class="material-icons">people</i><%= Flat.find(params[:id]).price_per_night %><i class="material-icons">euro_symbol</i></p>
    </div>
  </div>
</div>
  <form>
    <div class="form-group">
      <label for="formGroupExampleInput">Example label</label>
      <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder">
    </div>
    <div class="form-group">
      <label for="formGroupExampleInput2">Another label</label>
      <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input placeholder">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="path/to/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />



    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
        <%= link_to 'Simple AirBnb', flats_path %>
        <button>
          <%= link_to 'Add flat', new_flat_path %>
        </button>

    </div>

    <%= yield %>
  </body>
</html>